// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7hiVQQRB3R1Xw1CcqnkudkDb_eyMAJwg',
    appId: '1:479251514231:web:7b38b0c2a2d11d6c0d9772',
    messagingSenderId: '479251514231',
    projectId: 'avabot-8c496',
    authDomain: 'avabot-8c496.firebaseapp.com',
    storageBucket: 'avabot-8c496.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1TnEarRNqKDAP6GrZSAydfE4ZRclM04',
    appId: '1:479251514231:android:fe46ff028bf72cea0d9772',
    messagingSenderId: '479251514231',
    projectId: 'avabot-8c496',
    storageBucket: 'avabot-8c496.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkDeLhRINoUVxXrpakoBgYKzgSENJ3Qs',
    appId: '1:479251514231:ios:7f67f5c04bc2d62b0d9772',
    messagingSenderId: '479251514231',
    projectId: 'avabot-8c496',
    storageBucket: 'avabot-8c496.appspot.com',
    iosBundleId: 'com.example.avabot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkDeLhRINoUVxXrpakoBgYKzgSENJ3Qs',
    appId: '1:479251514231:ios:7f67f5c04bc2d62b0d9772',
    messagingSenderId: '479251514231',
    projectId: 'avabot-8c496',
    storageBucket: 'avabot-8c496.appspot.com',
    iosBundleId: 'com.example.avabot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7hiVQQRB3R1Xw1CcqnkudkDb_eyMAJwg',
    appId: '1:479251514231:web:e43294ea823e26bb0d9772',
    messagingSenderId: '479251514231',
    projectId: 'avabot-8c496',
    authDomain: 'avabot-8c496.firebaseapp.com',
    storageBucket: 'avabot-8c496.appspot.com',
  );
}
