// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4LS2lQ4Ds_n-SXp5aDnEQ-WFdLURkE8',
    appId: '1:79914860910:web:cfc0bc263f8eeb1e1e417f',
    messagingSenderId: '79914860910',
    projectId: 'shopbot-717d1',
    authDomain: 'shopbot-717d1.firebaseapp.com',
    storageBucket: 'shopbot-717d1.appspot.com',
    measurementId: 'G-EXTVB2M84D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZd1hPo8B3KpYPzRqB7y-Kne8_8kWDb3M',
    appId: '1:79914860910:android:a259fcae68d003b41e417f',
    messagingSenderId: '79914860910',
    projectId: 'shopbot-717d1',
    storageBucket: 'shopbot-717d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmZRZKwY6DJrLZV-Q7foQSbVAHNTok-Q',
    appId: '1:79914860910:ios:6dfc2367b21a2c0f1e417f',
    messagingSenderId: '79914860910',
    projectId: 'shopbot-717d1',
    storageBucket: 'shopbot-717d1.appspot.com',
    iosBundleId: 'com.example.avabot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmZRZKwY6DJrLZV-Q7foQSbVAHNTok-Q',
    appId: '1:79914860910:ios:6dfc2367b21a2c0f1e417f',
    messagingSenderId: '79914860910',
    projectId: 'shopbot-717d1',
    storageBucket: 'shopbot-717d1.appspot.com',
    iosBundleId: 'com.example.avabot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4LS2lQ4Ds_n-SXp5aDnEQ-WFdLURkE8',
    appId: '1:79914860910:web:e595e6d8826aa8dc1e417f',
    messagingSenderId: '79914860910',
    projectId: 'shopbot-717d1',
    authDomain: 'shopbot-717d1.firebaseapp.com',
    storageBucket: 'shopbot-717d1.appspot.com',
    measurementId: 'G-SKP6EG1PBK',
  );
}
